
import React from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Stethoscope, ClipboardList, FileText, Activity } from "lucide-react";
import { ReportAnalysis } from "./ScanReportDialog";

interface ReportAnalysisCardProps {
  analysis: ReportAnalysis;
}

const ReportAnalysisCard = ({ analysis }: ReportAnalysisCardProps) => {
  // Format confidence percentage for display
  const confidencePercent = Math.round(analysis.confidence * 100);
  
  // Determine confidence level for styling
  const confidenceLevel = 
    confidencePercent >= 90 ? "high" :
    confidencePercent >= 70 ? "medium" : "low";
  
  // Confidence level badge styling
  const confidenceBadgeVariant = 
    confidenceLevel === "high" ? "default" :
    confidenceLevel === "medium" ? "outline" : "destructive";

  return (
    <Card className="w-full">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="text-lg flex items-center">
            <Activity className="h-5 w-5 mr-2 text-primary" />
            AI Analysis Report
          </CardTitle>
          <Badge variant={confidenceBadgeVariant}>
            {confidencePercent}% Confidence
          </Badge>
        </div>
      </CardHeader>
      <CardContent className="space-y-4">
        <div>
          <h4 className="text-sm font-semibold flex items-center mb-1">
            <FileText className="h-4 w-4 mr-1 text-muted-foreground" />
            Summary
          </h4>
          <p className="text-sm">{analysis.summary}</p>
        </div>
        
        <div>
          <h4 className="text-sm font-semibold flex items-center mb-1">
            <Stethoscope className="h-4 w-4 mr-1 text-muted-foreground" />
            Diagnosis
          </h4>
          <p className="text-sm">{analysis.diagnosis}</p>
        </div>
        
        <div>
          <h4 className="text-sm font-semibold flex items-center mb-1">
            <ClipboardList className="h-4 w-4 mr-1 text-muted-foreground" />
            Recommendations
          </h4>
          <ul className="text-sm space-y-1 list-disc pl-5">
            {analysis.recommendations.map((recommendation, index) => (
              <li key={index}>{recommendation}</li>
            ))}
          </ul>
        </div>
        
        <div className="text-xs text-muted-foreground mt-4 pt-2 border-t">
          Note: This analysis is generated by AI and should be reviewed by a healthcare professional.
        </div>
      </CardContent>
    </Card>
  );
};

export default ReportAnalysisCard;
