// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jdwdzfdlvqhmbviidajc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impkd2R6ZmRsdnFobWJ2aWlkYWpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4OTk4NjcsImV4cCI6MjA2MDQ3NTg2N30.jTMC4a-CLcYQy_HqfPSq4iJ_7Ifp0P6KqquzCkjluDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);